### ISSUE TITLE
WPF神器居然是”无字天书“

### ISSUE THREAD

**Issue by sw554227643** [zLulus/My_Note#2]
@

**Comment by zLulus** [comment]
好吧～里面有些博客我确实只记了一个关键词，或者只是一些文章链接。Blend我只在学习WPF的时候试了一下，之后写WPF都还是用的VS……所以后续没有继续往里面填充内容。
当然我知道要做一些很炫的动画使用Blend体验up : ) 
同一个问题我也不会开两篇来水文章，而是在一篇里面重复迭代、更改。

如果对你造成了困扰我很抱歉～
@sw554227643
